FROM node:10.15-slim as build-stage
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
COPY . .
RUN ["npm", "run", "build-prod"]

FROM nginx:latest
RUN rm -rf /usr/share/nginx/html/*
RUN mkdir /usr/share/nginx/html/EstilosVidaSaludable
COPY --from=build-stage /usr/src/app/dist/frontend/index.html /usr/share/nginx/html/index.html
COPY --from=build-stage /usr/src/app/dist/frontend /usr/share/nginx/html/EstilosVidaSaludable/
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
